import "./globals.css";
import { Golos_Text, Unbounded } from "next/font/google";
import QueryWrapper from "./auth/QueryWrapper";

const golosText = Golos_Text({
  weight: ["400","700", "800"],
  preload: false,
  variable: "--font-golosText",
});
const unbounded = Unbounded({
  weight: ["700"],
  preload: false,
  variable: "--font-unbounded",
});

export const metadata = {
  title: "Taskify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en" className={`${unbounded.variable} ${golosText.variable}`}>
      <body>
        <QueryWrapper>
            {children}
        </QueryWrapper>
        </body>
      </html>
  );
}
